apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-secret-reader
  namespace: platform-secrets
subjects:
  - kind: ServiceAccount
    name: eso-k8s-store
    namespace: external-secrets-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-secret-reader