apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhdh-secrets
  namespace: developer-hub
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-platform-secrets
    kind: ClusterSecretStore
  target:
    name: rhdh-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        BACKEND_SECRET: "{{ .backendSecret }}"
        KEYCLOAK_BASE_URL: "{{ .keycloakBaseUrl }}"
        KEYCLOAK_REALM: "{{ .keycloakRealm }}"
        KEYCLOAK_CLIENT_ID: "{{ .keycloakClientId }}"
        KEYCLOAK_CLIENT_SECRET: "{{ .keycloakClientSecret }}"
        GIT_TOKEN: "{{ .gitToken }}"
        K8S_CLUSTER_NAME: "{{ .k8sClusterName }}"
        K8S_CLUSTER_URL: "{{ .k8sClusterUrl }}"
  data:
    - secretKey: backendSecret
      remoteRef:
        key: rhdh-seed-secret
        property: backendSecret
    - secretKey: keycloakBaseUrl
      remoteRef:
        key: rhdh-seed-secret
        property: keycloakBaseUrl
    - secretKey: keycloakRealm
      remoteRef:
        key: rhdh-seed-secret
        property: keycloakRealm
    - secretKey: keycloakClientId
      remoteRef:
        key: rhdh-seed-secret
        property: keycloakClientId
    - secretKey: keycloakClientSecret
      remoteRef:
        key: rhdh-seed-secret
        property: keycloakClientSecret
    - secretKey: gitToken
      remoteRef:
        key: rhdh-seed-secret
        property: gitToken
    - secretKey: k8sClusterName
      remoteRef:
        key: rhdh-seed-secret
        property: k8sClusterName
    - secretKey: k8sClusterUrl
      remoteRef:
        key: rhdh-seed-secret
        property: k8sClusterUrl