apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhdh-secrets
  namespace: developer-hub
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-platform-secrets
    kind: ClusterSecretStore
  target:
    name: rhdh-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        CLUSTER_DOMAIN: "{{ .clusterDomain }}"
        BACKEND_SECRET: "{{ .backstageBackendSecret }}"
        GIT_TOKEN: "{{ .backstageGitToken }}"
        GITHUB_ORG: "{{ .backstageGitOrg }}"
        SCAFFOLDER_TEST_TOKEN: "{{ .scaffolderTestToken }}"
  data:
    - secretKey: clusterDomain
      remoteRef:
        key: platform-seed-secret
        property: clusterDomain
    - secretKey: backstageBackendSecret
      remoteRef:
        key: platform-seed-secret
        property: backstageBackendSecret
    - secretKey: backstageGitToken
      remoteRef:
        key: platform-seed-secret
        property: backstageGitToken
    - secretKey: backstageGitOrg
      remoteRef:
        key: platform-seed-secret
        property: backstageGitOrg
    - secretKey: scaffolderTestToken
      remoteRef:
        key: scaffolder-test-token
        property: scaffolderTestToken